# HLint configuration file
# Format: https://github.com/ndmitchell/hlint/blob/master/data/default.yaml

## HLint hints we don't care about

- ignore:
    name: Eta reduce
- ignore:
    name: Use list comprehension
- ignore:
    name: Use newtype instead of data
- ignore:
    name: Reduce duplication
- ignore:
    name: Redundant do
