# stylish-haskell configuration file
# ref: https://github.com/jaspervdj/stylish-haskell/blob/master/data/stylish-haskell.yaml

steps:
  # Align the right hand side of some elements.  This is quite conservative
  # and only applies to statements where each element occupies a single
  # line.
  - simple_align:
      cases: false
      top_level_patterns: false
      records: true

  - imports:
      align: none
      long_list_align: new_line_multiline
      list_padding: 4
      separate_lists: false

  - language_pragmas:
      align: false
      remove_redundant: true

  - tabs:
      spaces: 8

  - trailing_whitespace: {}

newline: lf
