defaults:
  local: ../hpack.yaml

name: aeson-schemas
version: 0.1.0

dependencies:
- aeson
- base
- bytestring
- first-class-families
- megaparsec
- template-haskell
- text
- unordered-containers

library:
  source-dirs: src
  other-modules:
    - Data.Aeson.Schema.TH.Get
    - Data.Aeson.Schema.TH.Schema
    - Data.Aeson.Schema.TH.Unwrap

tests:
  aeson-schemas-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
      - aeson-schemas
      - tasty
      - tasty-golden
