name: aeson-schemas
version: 1.4.2.0
verbatim:
  cabal-version: '>= 1.10'
license: BSD3
license-file: LICENSE.md
author:
  - Brandon Chinn <brandonchinn178@gmail.com>
maintainer:
  - Brandon Chinn <brandonchinn178@gmail.com>
category: JSON
synopsis: Easily consume JSON data on-demand with type-safety
description: |
  Parse JSON data easily and safely without defining new data types. Useful
  for deeply nested JSON data, which is difficult to parse using the default
  FromJSON instances.
extra-source-files:
  - README.md
  - CHANGELOG.md
  - examples/*.json
  - test/**/*.golden
  - test/wont-compile/*.hs

github: brandonchinn178/aeson-schemas

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances
  - -Wunused-packages

library:
  source-dirs: src
  other-modules:
    - Data.Aeson.Schema.TH.Enum
    - Data.Aeson.Schema.TH.Get
    - Data.Aeson.Schema.TH.Getter
    - Data.Aeson.Schema.TH.Parse
    - Data.Aeson.Schema.TH.Schema
    - Data.Aeson.Schema.TH.Unwrap
    - Data.Aeson.Schema.TH.Utils
  dependencies:
    - aeson < 3
    - base >= 4.17 && < 5
    - first-class-families < 0.9
    - hashable < 1.5
    - megaparsec < 10
    - template-haskell < 2.22
    - text < 2.2
    - unordered-containers < 0.3

tests:
  aeson-schemas-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
      - aeson
      - aeson-qq >= 0.8.4
      - aeson-schemas
      - base
      - deepseq
      - filepath
      - hint
      - interpolate
      - process
      - QuickCheck
      - raw-strings-qq
      - tasty
      - tasty-golden
      - tasty-hunit
      - tasty-quickcheck >= 0.8.1
      - template-haskell
      - temporary
      - text
      - th-orphans
      - th-test-utils
    when:
      # https://github.com/haskell-hint/hint/issues/149
      - condition: impl(ghc < 9.2)
        dependencies:
          - hint < 0.9.0.6

benchmarks:
  aeson-schemas-bench:
    source-dirs: bench
    main:        Main.hs
    dependencies:
      - aeson
      - aeson-schemas
      - base
      - criterion
      - deepseq
      - template-haskell
      - th-test-utils
