resolver: lts-21.1

flags:
  aeson-schemas:
    run-integration-tests: true

ghc-options:
  # TODO: Move -Wunused-packages into package.yaml
  # https://github.com/haskell/cabal/issues/9082
  '$locals': -Werror -Wunused-packages
