name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

jobs:
  ghc_compat_test:
    strategy:
      matrix:
        ghc_version:
          - '9.8'
          - '9.10'
          - '9.12'
        include:
          - ghc_version: 9.8.1
            oldest: true

    name: ghc_compat_test (${{ matrix.ghc_version }})
    uses: ./.github/workflows/ghc-compat-test.yml
    with:
      ghc_version: ${{ matrix.ghc_version }}
      oldest: ${{ matrix.oldest || false }}

  lint:
    runs-on: ubuntu-latest
    env:
      FOURMOLU_VERSION: '0.12.0.0'
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Install fourmolu
        run: |
          curl -fsSL \
            "https://github.com/fourmolu/fourmolu/releases/download/v${FOURMOLU_VERSION}/fourmolu-${FOURMOLU_VERSION}-linux-x86_64" \
            -o /usr/local/bin/fourmolu
          chmod +x /usr/local/bin/fourmolu
      -
        name: Run fourmolu
        run: fourmolu -m check .

  benchmarks:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-benchmarks-${{ hashFiles('stack.yaml', 'package.yaml') }}
      -
        name: Run benchmarks
        run: stack bench --ghc-options=-Werror --ba '--output=/tmp/benchmark-results.html'
      -
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: /tmp/benchmark-results.html

  check_sdist:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        id: setup
        name: Set up GHC
        uses: haskell-actions/setup@v2
      -
        name: Strip unreleased section from CHANGELOG
        run: sed -i -n '/^# Unreleased/d; /^#/,$p' CHANGELOG.md
      -
        name: Create sdist bundle
        run: cabal sdist --output-directory=.
      -
        uses: actions/upload-artifact@v3
        with:
          name: aeson-schemas-sdist
          path: aeson-schemas-*.tar.gz
