name: Release
on: workflow_dispatch

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - ci

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/download-artifact@v3
        with:
          name: aeson-schemas-sdist
          path: ./sdist/

      - name: Load package version
        run: scripts/GetVersion.hs
        id: version_info

      - name: Load Hackage token secret name
        run: |
          import re
          username = "${{ github.actor }}"
          secret_name = "HACKAGE_TOKEN_" + re.sub(r"\W+", "_", username).upper()
          print(f"::set-output name=secret_name::{secret_name}")
        shell: python
        id: hackage_token_secret

      - name: Make release
        run: scripts/make-release.sh
        env:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          hackage_token: ${{ secrets[steps.hackage_token_secret.outputs.secret_name] }}
          version: ${{ steps.version_info.outputs.version }}
          sdistdir: ./sdist/
