name: Release
on: workflow_dispatch

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - ci

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/download-artifact@v3
        with:
          name: aeson-schemas-sdist
          path: ./sdist/

      - uses: brandonchinn178/haskell-actions/parse-cabal-file@parse-cabal-file
        id: cabal_file
        with:
          cabal_file: aeson-schemas.cabal
      - name: Set version label
        run: echo 'VERSION=v${{ steps.cabal_file.outputs.version }}' >> "${GITHUB_ENV}"

      - name: Get CHANGELOG section
        run: |
          sed '/^# Unreleased/,/^$/d' CHANGELOG.md > /tmp/changelog-without-unreleased
          if [[ "$(head -n 1 /tmp/changelog-without-unreleased)" != "# ${VERSION}" ]]; then
            echo "CHANGELOG doesn't look updated" >&2
            exit 1
          fi
          sed '1 d; /^# v/,$ d' /tmp/changelog-without-unreleased > /tmp/changelog-body

      - uses: brandonchinn178/haskell-actions/hackage-upload@hackage-upload
        with:
          archive: sdist/aeson-schemas-*.tar.gz
          token: ${{ secrets.HACKAGE_TOKEN_LEAPYEAR }}

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          body_path: /tmp/changelog-body
          draft: true
          target_commitish: ${{ github.sha }}
